version: '3.8'
services:
 postgres:
  container_name: quotes-database
  build:
   context: ./database
  networks: 
   - quote-app
 backend:
  container_name: quotes-backend
  build:
   context: ./backend
  ports:
   - 8080:8080
  env_file: ./backend/env/backend.env
  networks: 
   - quote-app
  depends_on:
   - postgres
 frontend:
  container_name: quote-frontend
  build:
   context: ./frontend
  ports:
   - 80:80
  networks: 
   - quote-app
  depends_on:
   - backend 

networks:
 quote-app: